python trainer.py \
    --data_path="LAFAN1/output/BVH" \   # where the BVH for training can be found
    --dataset="LAFAN1" \
    --processed_data_dir="processed_data_lafan/" \
    --window=70 \
    --batch_size=32 \
    --epochs=5000 \             # can consider fewer epochs
    --device=1 \
    --entity_name=lafan1_trial \
    --exp_name="LAFAN1" \
    --save_interval=20 \        # checkpoint after this many steps
    --learning_rate=0.0001 \
    --loss_cond_weight=1.5 \
    --loss_pos_weight=0.05 \
    --loss_rot_weight=2.0 \
    --from_idx=9 \
    --target_idx=68 \
    --interpolation='slerp'
